name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature-set: ["--no-default-features", "--features sha-crypt", "--features argon2", "--features sha-crypt,argon2,syslog"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Clippy
        run: cargo clippy --all-targets ${{ matrix.feature-set }} -- -D warnings
        shell: bash
      - name: Test
        run: |
          set -euo pipefail
          echo "== Testing feature set: '${{ matrix.feature-set }}' =="
          if [ "${{ matrix.feature-set }}" = "--no-default-features" ]; then
            echo "(Info) No hashing features enabled: integration tests are feature-gated and will be skipped."
          fi
          ALLOW_NON_ROOT=1 cargo test ${{ matrix.feature-set }}
        shell: bash
      - name: Fmt
        run: cargo fmt -- --check
